### ISSUE TITLE
Disney+ support

### ISSUE THREAD

**Issue by andrikos** [VarunS2002/Xposed-Disable-FLAG_SECURE#1] opened 2021-04-10 23:19 UTC
Is this supposed to work with Disney+ ? 
I still can't take a screenshot

Thanks

**Comment by VarunS2002** [comment] 2021-04-11 09:38
@andrikos Can you share some more details.
1. What Xposed are you using and in which mode
2. Xposed module logs

**Comment by andrikos** [comment] 2021-04-11 18:06
@VarunS2002 
1. Riru - EdXposed 0.5.2.2_4683-master as Magisk module
2. How can I gather such logs?

BTW, it works for Chrome incognito and other bank apps.
Thus, I believe there is something special with Disney+ app.

**Comment by VarunS2002** [comment] 2021-04-12 02:09
@andrikos 
![image](https://user-images.githubusercontent.com/30069380/114331663-1d8fdd80-9b62-11eb-88ab-b0130c1f8f01.png)

- Hamburger menu
- Module logs
- Save it and upload it here

**Comment by andrikos** [comment] 2021-04-13 11:17
[EdXposed_Modules_20210413_131623.txt](https://github.com/VarunS2002/Xposed-Disable-FLAG_SECURE/files/6303300/EdXposed_Modules_20210413_131623.txt)

**Comment by VarunS2002** [comment] 2021-04-13 12:05
@andrikos The module doesn't seem to be activated properly. 
I have faced this before, this is not a module issue most probably.
Try reinstalling the module and reinstalling Riru and EdXposed if the issue still persists.
This had fixed it for me.

**Comment by andrikos** [comment] 2021-04-14 21:33
I reinstalled:
1. Riru 25.4.1.r141.22618ad
2. Riru - EdXposed 0.5.2.2_4683-master
3. Disable-FLAG_SECURE 2021-04-11

I am able to take screenshots in Chrome incognito correctly.
In Disney+ I can also get a screenshot, but the video part is black.
You can find attached a screenshot and the updated module logs.

![Screenshot_20210414-233029](https://user-images.githubusercontent.com/3123918/114782159-e72cab00-9d79-11eb-8fe2-77831bf584da.png)

[EdXposed_Modules_20210414_233312.txt](https://github.com/VarunS2002/Xposed-Disable-FLAG_SECURE/files/6313811/EdXposed_Modules_20210414_233312.txt)

**Comment by VarunS2002** [comment] 2021-04-15 08:20
@andrikos 
Have you added this app to the blacklist? Then remove it else this module won't work <br>
![image](https://user-images.githubusercontent.com/30069380/114837008-db300000-9df0-11eb-8180-471ffc9d3096.png)
If not then
Enable Activation Scope for this module and select only Android system and Disney+ and restart
Then add the log if it's still not working
Also disable "Pass SafetyNet" 
Tell me if you need help

**Comment by andrikos** [comment] 2021-04-15 16:22
It is already as you describe
![Screenshot_20210415-182112](https://user-images.githubusercontent.com/3123918/114904176-dfbbdf00-9e17-11eb-98ed-b155317addaa.png)

**Comment by VarunS2002** [comment] 2021-04-16 04:21
@andrikos 
Did you try Activation Scope?

**Comment by VarunS2002** [comment] 2021-04-28 15:29
@andrikos I will be closing this issue in 2 more days due to inactivity

**Comment by andrikos** [comment] 2021-04-28 15:58
Yes I did try.
The only app where screenshot/cast doesn't work is Disney.
I suspect they really enforce DRM, but I don't know how.

Regards,
Nick

--
=Do-
N.AND

**Comment by VarunS2002** [comment] 2021-04-28 16:11
@andrikos I still think this app should support Disney+ as your logs show it's not being enabled for Android System Framework.
If this is the main problem then the app shouldn't work in Telegram Secret Chat Disappearing Media either.
I saw you have other Disable flag secure modules too. Did you try disabling them?

**Comment by andrikos** [comment] 2021-04-28 18:43
Give me a couple of days and I'll provide the new logs, ok?
Thanks!

--
=Do-
N.AND

**Comment by VarunS2002** [comment] 2021-04-28 18:44
@andrikos Sure no problem!

**Comment by andrikos** [comment] 2021-04-28 22:03
1 Default configuration
[1 default.txt](https://github.com/VarunS2002/Xposed-Disable-FLAG_SECURE/files/6395038/1.default.txt)

2 After I enabled scope for android system and Disney+
[2 scope.txt](https://github.com/VarunS2002/Xposed-Disable-FLAG_SECURE/files/6395050/2.scope.txt)

3 After I also disabled " pass safety net"  in edexposed manager
[3 nopass.txt](https://github.com/VarunS2002/Xposed-Disable-FLAG_SECURE/files/6395058/3.nopass.txt)


In all cases I can get a Disney+ screenshot but the video part is black: 
![Screenshot_20210428-235238](https://user-images.githubusercontent.com/3123918/116478231-0d743f80-a87e-11eb-8fd7-ad0cdce912e8.png)

In the first case, I could take screenshot of Chrome incognito mode, in the other two I couldn't.

Lat me know of anything extra you need

**Comment by VarunS2002** [comment] 2021-04-29 11:22
@andrikos 
Your EdXposed doesn't seem to be working correctly as everything is under the crash section.
Only in default configuration, logging seems to have happened correctly.<br>
![image](https://user-images.githubusercontent.com/30069380/116541201-c8491f80-a908-11eb-8a24-79dd81602f26.png)

1. In the Manager Settings, set yours same as this:

![image](https://user-images.githubusercontent.com/30069380/116542290-21fe1980-a90a-11eb-9262-b596d655d533.png)

2. In the Modules section disable everything except this module

3. Enable Activation Scope for this module and select the same apps mentioned below:

4. In the Xposed Hide section enable these apps only: (Disney+ instead of Prime Video in your case)

![image](https://user-images.githubusercontent.com/30069380/116542658-8620dd80-a90a-11eb-85d3-604a14a87ef4.png)
![image](https://user-images.githubusercontent.com/30069380/116542607-70abb380-a90a-11eb-979c-dd8af1957dae.png)
![image](https://user-images.githubusercontent.com/30069380/116542707-933dcc80-a90a-11eb-89e5-6d62e71ca7f3.png)

5. Restart and then send logs of both these sections:

![image](https://user-images.githubusercontent.com/30069380/116543157-2545d500-a90b-11eb-822d-f08c5b12f6cf.png)

**Comment by VarunS2002** [comment] 2021-04-29 11:29
@andrikos Also try other modules like to see if they work, keep only 1 disable flag secure module enabled at one time
https://github.com/LSPosed/DisableFlagSecure/releases/tag/v1.0.1
https://repo.xposed.info/module/fi.veetipaananen.android.disableflagsecure
https://repo.xposed.info/module/fi.veetipaananen.android.disableflagsecure2

**Comment by VarunS2002** [comment] 2021-04-29 11:39
@andrikos 
The problem seems to be that the module is not getting applied on Android System.
It is only getting applied on Disney+
Logs contain this:
`EdXposed-Bridge: Disabled FLAG_SECURE for: com.disney.disneyplus`
It should also contain this:
`EdXposed-Bridge: Disabled FLAG_SECURE for: android`
Only then it is expected to work correctly

**Comment by andrikos** [comment] 2021-04-29 12:39
[modules.txt](https://github.com/VarunS2002/Xposed-Disable-FLAG_SECURE/files/6398563/modules.txt)
[verbose.txt](https://github.com/VarunS2002/Xposed-Disable-FLAG_SECURE/files/6398565/verbose.txt)

The logs after I followed your instructions.
I still get black on the video part.
The logs show that your module is properly applied, no?

**Comment by VarunS2002** [comment] 2021-04-29 12:46
@andrikos This time the log is perfect and the app is expected to function properly.
But it's still black, well that's unfortunate ☹️.
I'll try to see what the issue is, meanwhile try the other 3 apps I suggested.
If any of them work I can check the code and find the problem in my app to fix it.

**Comment by VarunS2002** [comment] 2021-04-29 12:51
@andrikos When you try these 3 apps, do the same steps that I mentioned that you did for this.

**Comment by VarunS2002** [comment] 2021-05-06 11:34
@andrikos 
[app-debug.zip](https://github.com/VarunS2002/Xposed-Disable-FLAG_SECURE/files/6434054/app-debug.zip)
Extract the apk from the zip
Uninstall the existing app and try this one with the same steps above

**Comment by VarunS2002** [comment] 2021-05-11 10:35
@andrikos Did you try the test version?

**Comment by andrikos** [comment] 2021-05-11 11:15
[EdXposed_Modules_20210511_131227.txt](https://github.com/VarunS2002/Xposed-Disable-FLAG_SECURE/files/6458733/EdXposed_Modules_20210511_131227.txt)

![Screenshot_20210511-131145](https://user-images.githubusercontent.com/3123918/117806595-d4af6f80-b25a-11eb-8ced-992cca460e21.png)

Logs and screenshot with your file

**Comment by VarunS2002** [comment] 2021-05-11 11:45
@andrikos Did any of those 3 work for you?
Because if not, I'm unable to fix this :(
The last thing you can do is try LSPosed

**Comment by andrikos** [comment] 2021-05-11 12:37
I'm afraid none of them worked :(
BTW, are the exceptions in the logs expected?

**Comment by VarunS2002** [comment] 2021-05-11 12:42
@andrikos That's very unfortunate.
Yes they are expected.
I suggest you to open an issue [here](https://github.com/LSPosed/DisableFlagSecure) as this was active recently.
Probably he can solve the problem. 
Consequently I can integrate the solution in my app too.

**Comment by VarunS2002** [comment] 2021-05-12 11:22
@andrikos 
Try [this](https://github.com/VarunS2002/Xposed-Disable-FLAG_SECURE/files/6465482/app-release.zip) as it worked out for #3

**Comment by VarunS2002** [comment] 2021-05-12 11:48
@andrikos Nevermind the app doesn't seem to support Disney+

> @andrikos That's very unfortunate.
> Yes they are expected.
> I suggest you to open an issue [here](https://github.com/LSPosed/DisableFlagSecure) as this was active recently.
> Probably he can solve the problem.
> Consequently I can integrate the solution in my app too.

This seems like the best bet

**Comment by programminghoch10** [comment] 2021-05-14 17:18
Hello,
I got some news on this topic.
A friend and me did two days of research, searching through the decompiled source code of Disney+.
We've found out that Disney uses proprietary DRM decoding of the device and somehow pushes this directly to the internal display.
This has nothing to do with flag secure.
When testing the same on a very old phone, which does not have this hardware DRM stuff, it works normally as it should.
So this is more of deep DRM android stuff than flag secure.

**Comment by programminghoch10** [comment] 2021-05-14 17:42
Okay so we found the culprit.

> When testing the same on a very old phone, which does not have this hardware DRM stuff, it works normally as it should.

This was a very important piece of information.
It told us, that the device must be using hardware decryption capabilites.

Now onto the point of how to prevent this.
I thought those hardware decryption libraries must be placed in vendor files/partition.
And there is actually a Magisk module, which does systemlessly replace those files with a zero-byte replacement.

It is called [`liboemcrypto.so disabler`](https://github.com/Magisk-Modules-Repo/liboemcryptodisabler) and with this installed and this module (v2.0.0) screensharing Disney+ works too.

@andrikos Please install [`liboemcrypto.so disabler`](https://github.com/Magisk-Modules-Repo/liboemcryptodisabler) in Magisk and make sure the Flag-Secure v2 XPosed module is enabled on system framework and Disney+ and try it again.

If it works @VarunS2002 can include this as a notice in the README (or please let me do it so I can be listed as a contributor ;) and we can close this issue.

Also here is screenshot proof:
![image](https://user-images.githubusercontent.com/16062290/118308814-af399480-b4ec-11eb-99a9-357b3a5cf811.png)

**Comment by andrikos** [comment] 2021-05-14 23:32
@programminghoch10 
Thanks for all the analysis!
Your solution does indeed work in that I can make screenshots of Disney+ content.

The problem is that my DRM level falls to L3 which makes Disney+ show in low resolution.
This is equivalent to watch low resolution on PC through a web browser.
What I'm really trying to accomplish here is watch high quality video on my PC, and I've been trying to stream the high quality content from my Android through Cast capability :(

**Comment by programminghoch10** [comment] 2021-05-15 00:27
@andrikos 

> The problem is that my DRM level falls to L3 which makes Disney+ show in low resolution.
> This is equivalent to watch low resolution on PC through a web browser.

Well it seems this is a limit of this method...
I don't know if I am capable of doing anything about it;
DRM is not made to be easily broken or modded as you might guess...
Also the whole DRM thing is proprietary and without the source it will be hard to see what it does at all.
Aaaaand the big companies fund this to be secure, so as soon as we break L1 in a way it's not intended to they will probably introduce L0 and downgrade L1 to low quality, so it's all over again...

Your original problem is solved though, as you are now able to cast Disney+.

**Comment by VarunS2002** [comment] 2021-05-15 09:44
@programminghoch10 That's very impressive thanks mate! I'll merge it shortly and make some changes.
@andrikos Thanks to you too for your testing.

**Comment by VarunS2002** [comment] 2021-05-15 10:11
@andrikos @programminghoch10 Does Netflix also require the magisk module?

**Comment by VarunS2002** [comment] 2021-05-15 10:32
@programminghoch10 Also out of curiosity, what did you use to decompile the app?

**Comment by programminghoch10** [comment] 2021-05-15 11:47
@VarunS2002 

> Does Netflix also require the magisk module?

On some devices, yes.

> what did you use to decompile the app?

[jadx](https://github.com/skylot/jadx)

**Comment by VarunS2002** [comment] 2021-05-15 13:53
@programminghoch10 Thanks. I've merged your PR and made some changes too.

**Closed as completed by VarunS2002** 2021-05-15 13:53 UTC
Labels: bug
